### ISSUE TITLE
Usage in other projects

### ISSUE THREAD

**Issue by bbss** [oakes/paren-soup#1]
This is a kind of beginner question and I am not sure if this is the right place to ask, but I run into problems trying to use paren-soup in another project.

I would like to use paren-soup inside devcards. I've tried the lein dep 0.1.2 , and running lein install inside the cloned repo (0.1.3) inside the project I want to use it in.

I get 

```
Compile Error
clojure.lang.ExceptionInfo : failed compiling file:src/devc/core.cljs
clojure.lang.ExceptionInfo : Referred var cljs.tools.reader/*wrap-value-and-add-metadata?* does not exist
Error on file , line , column
```

I've downloaded cljs.jar and put it inside the projects root assuming that is what was needed because of: ", but you will need to build your own copy of ClojureScript until a version is released with this patch.". 

But it didn't make a difference, any pointers of what to try next?

**Comment by oakes** [comment]
I had to fork tools.reader so in your dependencies vector, try excluding it like this:

``` clojure
[org.clojure/clojurescript "1.7.48"
 :exclusions [org.clojure/tools.reader]]
```

**Comment by oakes** [comment]
By the way, I don't know what you mean by putting the cljs.jar inside your project's root. You shouldn't need to build the compiler at all because a prebuilt version is already in this project.

**Comment by oakes** [comment]
Let me know if you need any more help with this.

**Comment by bbss** [comment]
Oops, overlooked your response. I will give it another shot. Thanks!

**Comment by chr15m** [comment]
@bbss did you make any progress? I would like to document this properly on #6 and issue a PR.

**Comment by bbss** [comment]
@chr15m I ended up copying the approach in the example repo for parinfer.
