### ISSUE TITLE
Requiring results in could not analyze error

### ISSUE THREAD

**Issue by syngrato** [oakes/paren-soup#11]
I am using ClojureScript 1.9.229 and paren-soup 2.10.3.
Requiring paren-soup results in:
`No such namespace: clojure.spec.alpha, could not locate clojure/spec/alpha.cljs, clojure/spec/alpha.cljc, or Closure namespace "clojure.spec.alpha"`

**Comment by oakes** [comment]
You will need to use the latest version of cljs, which is 1.9.946.

**Comment by maacl** [comment]
Thanks, you might want to note that in the readme.
