### ISSUE TITLE
Demo not up to date

### ISSUE THREAD

**Issue by Grahack** [oakes/paren-soup#2]
Hi,
I wanted to tell you that some colors were too light in the light theme, but it seems that your repo already contains the color "gold" for numbers instead of "FFD700".
So maybe your demo uses some old code?
I tried to investigate the gh-pages branch but the files seem to be both at "Hide the scroll bars".
I'm missing something, but what?

**Comment by oakes** [comment]
I believe the demo has the latest changes. Please let me know if you notice specific problems though.

**Comment by Grahack** [comment]
Sorry, you are right, the demo is up to date.
What I didn't understand was that the `gold` color specified in the CSS was reported as `FFD700` in my inspector. But it is the hex for `gold` indeed.

What I wanted to say at first is that I found the colors of the light theme too light. See my screen:

<img width="960" alt="paren-soup" src="https://cloud.githubusercontent.com/assets/148334/11325378/5846ae2a-914c-11e5-87f5-f3abea325025.png">
