### ISSUE TITLE
Documentation for integrating this into an existing ClojureScript project

### ISSUE THREAD

**Issue by chr15m** [oakes/paren-soup#6]
Assuming a start like this:

 * Add `[paren-soup "2.8.6"]` to your dependencies.

What comes next?

Can this be hosted as a sub section of an existing page?

How do I invoke the compiler loop from ClojureScript? (the example shows how to do it with plain HTML & Javascript)

Can I provide context such as already defined `defn`s and `def`s?

Is there an example Hiccup form for generating the required HTML?

Once I know the answer to these questions I will write up some documentation and issue a PR.

**Comment by oakes** [comment]
[Nightlight](https://github.com/oakes/Nightlight) uses paren-soup as a clojurescript library, so looking at that code may be a good place to start. I'm currently on a cross-country road trip so I cannot elaborate at the moment.

**Comment by chr15m** [comment]
No worries, thanks!

**Comment by oakes** [comment]
I added an explanation in the README for using paren-soup within a ClojureScript project. Please let me know if I can help further.
