### ISSUE TITLE
Doesn't recognise "%integer" in anonymous function

### ISSUE THREAD

**Issue by hanyuone** [oakes/paren-soup#7]
I have this code in `paren-soup`:

```clojure
(defn prime? [n]
  (if (< n 2) false
    (not
      (reduce #(or % %2)
        (for [a (range 2 n)]
          (zero? (mod n a)))))))
```

For some reason, there's an error in the anonymous function, `#(or % %2)`, at the `%2`:

    Arg literal must be %, %& or %integer

But the arg literal is `%integer`.

The code works perfectly on `clojurescript.io`, which recognises the `%2`.

**Comment by oakes** [comment]
Just fixed it and released version 2.8.9. I'll be releasing a new version of Nightcode with the fix soon as well. Thank you!
